language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
install:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt -- --check
  - cargo clippy
  - cargo test

notifications:
  email:
    recipients:
      - michael@mbh.sh
    on_success: never # default: change
    on_failure: always # default: always