# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2
language: rust
rust:
  - 1.38.0  # min. guaranteed working version
  - stable
  - beta
  - nightly
dist: bionic
services: docker
sudo: required

env:
  global:
    - PROJECT_NAME: rasusa
    - RUST_BACKTRACE: full
    - IMAGE_NAME: mbhall88/rasusa

addons:
  apt:
    update: true
    packages:
      # Dependencies for kcov
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - musl-tools  # For building MUSL static builds on Linux.

matrix:
  fast_finish: true
  include:
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
      rust: stable
    - os: osx
      env: TARGET=x86_64-apple-darwin
      rust: stable

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

after_success:
  - bash ci/after_success.sh

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  - provider: releases
    file_glob: true
    file: $PROJECT_NAME-$TRAVIS_TAG-$TARGET.*
    skip_cleanup: true
    on:
      condition: $TRAVIS_RUST_VERSION = stable
      branch: master
      tags: true
    api_key:
      secure: "i7dLFxAv1V+ODvwIPQJQ33iO5aoL4R7rjYNPZ7mkf6AB15MbDnYkly7MpsaTxfQmUPoBBpuHFXGEVInXfBfm/8hqrY2D0EBsr3yhBaTgLfuXf2kIj9LX+BSHqO2/JXmKWeLZcFa2aFrBXz154818vCzvvcR0r0HIBQgOA5gtU46uSXSyOqDAqrF4eRuLEXt2SYmgCRGi265j3+mm9wYjCLbHJT34bkMJQa4kqygnMDBTi4yblAWR1PqGvFWi2Ot4yAikHgg+bbNZRdRZzCBhkgozhvSI2syyli/l0P6fjqR4GhnrLKHyyy4vGAf+Zad/GL45MEbh5qmV8vLkmE39OZgQ/GT73Psl01PGohFe13CdAXf9/zZanmVMXHguYkAXDUnaHlMIbz/KEkjlWJqf7yWU6c/7Hh7DSvYtQp28G7s4CN5qR89a6esl7F2UdkFrpScQMUme8PVhwV6a6DW5ZDlPIZk31rWTBJvk321kyT5VyEuQ7nf2yYdJaOP+2bsbQrF0def4m4ZJ6NuxI2mD8ozqgR4pi2DI6ELyVQ9QQWcsk/KZJdgn/h+I2POQDoMvHcMfxPGn8uk7Dt092t9knvaLAC5vInd4M/4iauBMJdKdHBwJelHVUHvhs4qUQT1mLDPyCqQq7Dngabvytw/pITeFN+PDpdmNbsbPAc340fY="
  - provider: script
    script: bash ci/docker_push.sh
    on:
      condition: $TARGET = x86_64-unknown-linux-musl
      branch: master
      tags: true
  - provider: cargo
    on:
      tags: true
      branch: master
      condition: $TARGET = x86_64-unknown-linux-musl
    token:
      secure: jPvxYnImwNcYaqoOzq9GHahkkCID8KdOUDf/qsohNsUsUzKmy039EGtyCcav9oPQAe/4KqPmDvS1KJBoR3C/WBHnT1exSq0ZUIxvTxwodC2akjECvfoXrz3cMSqz1J0BSmf7r/mW0ZJITFLBvu1GCy+7oB4BecS9d8pgP9lIJ8ftp4FmdoFBAQKEfjfMc8RW9hXWOfXT2RgIf22UVP7I+gibdkMU4Rdk2IuQZyAv2PcSJVY6+2aQchIN28BGHS0GI0mH8YqsH9fJiSLvvv/sKgdUjcEEcnqwt9N/430y3QP9Nd4jRLWCAJBppBxwj47fGxMPvQBpKVCj4Xm6nrzRXjSv0DaLVRuM10fGeK2gDNPe/zgLYfuSwDSl6Fe+SFindWzl03CiJGCOAgT1NDLjXfMbBYuTWa2prO8qv3aXl19FDmCcDwh5Mb1A9rPnwJCaCqo+90OMpGnPEwuXPcxGezaj69UGtXr0qskLlpj1V0ib1yZk5KpVF6jxOLYbOJWb6NVj9dyoKXnHI6XC2CZIZxbClqXcZhbpnSbqPtHldeW0Y8g5Izm8IDB9WqdkUatH3JNpcQrBhFaTPyFHTZ8klzc7oUekCm48b/ncivHtlGloqbGf/x7RclbFpqa+pYjaU8SGs3jk2IBLf96q6r64AFuyp1oqKpnexTJ6VVR/CRU=


cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    recipients:
      - michael@mbh.sh
    on_success: never # default: change
    on_failure: always # default: always
