[package]
name = "rasusa"
version = "0.1.0"
authors = ["Michael Hall <michael@mbh.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[badges]
travis-ci = { repository = "mbhall88/rasusa" }

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
regex = "1"
