[package]
name = "rasusa"
version = "0.1.0"
authors = ["Michael Hall <michael@mbh.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[badges]
travis-ci = { repository = "mbhall88/rasusa" }
codecov = { repository = "mbhall88/rasusa", branch = "master", service = "github" }

[dependencies]
structopt = "0.3.2"
clap = "2.33.0"
regex = "1"
snafu = "0.5.0"
bio = "0.29.0"
failure = "0.1.5"
exitfailure = "0.5.1"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
